import { Appearance, ICatalogItem } from 'tools/types/api-catalog-items-types';

export const CATALOG_ITEMS: ICatalogItem[] = [
  {
    id: '0',
    name: 'Header',
    url: '/',
    groups: [''],
    accent: Appearance.PLAIN,
  },
  {
    id: '1',
    name: 'Каталог',
    url: '/',
    groups: ['Header'],
    accent: Appearance.ACCENT,
    svg: '',
  },
  {
    id: '2',
    name: 'Акции',
    url: '/',
    groups: ['Header'],
    accent: Appearance.HIGHLIGHT,
    svg: '',
  },
  {
    id: '3',
    name: 'Сладости, десерты, мороженое',
    url: '/',
    groups: ['Header', 'Каталог'],
    accent: Appearance.PLAIN,
  },
  {
    id: '4',
    name: 'Кулинария',
    url: '/',
    groups: ['Header', 'Каталог'],
    accent: Appearance.PLAIN,
  },
  {
    id: '5',
    name: 'Добрые покупки',
    url: '/',
    groups: ['Header', 'Каталог'],
    accent: Appearance.PLAIN,
  },
  {
    id: '6',
    name: 'Праздник',
    url: '/',
    groups: ['Header'],
    accent: Appearance.ACCENT,
  },
  {
    id: '7',
    name: 'Вакансии',
    url: '/',
    groups: ['Header'],
    accent: Appearance.ACCENT,
    svg: '',
  },
  {
    id: '8',
    name: 'Доставка',
    url: '/',
    groups: ['Header'],
    accent: Appearance.PLAIN,
    svg: '',
  },
  {
    id: '9',
    name: 'Магазины',
    url: '/',
    groups: ['Header'],
    accent: Appearance.PLAIN,
    svg: '',
  },
  {
    id: '10',
    name: 'Меню',
    url: '/',
    groups: ['Header'],
    accent: Appearance.PLAIN,
    svg: '',
  },
  {
    id: '11',
    name: 'Новинки',
    url: '/',
    groups: ['Каталог'],
    accent: Appearance.PLAIN,
  },
  {
    id: '12',
    name: 'Хиты',
    url: '/',
    groups: ['Каталог'],
    accent: Appearance.PLAIN,
  },
  {
    id: '13',
    name: 'Алкоголь',
    url: '/',
    groups: ['Каталог', 'Новинки', 'Хиты'],
    accent: Appearance.PLAIN,
  },
  {
    id: '14',
    name: 'Бакалея',
    url: '/',
    groups: ['Каталог', 'Новинки', 'Хиты'],
    accent: Appearance.PLAIN,
  },
  {
    id: '15',
    name: 'Пиво, медовуха',
    url: '/',
    groups: ['Алкоголь', 'Новинки', 'Хиты'],
    accent: Appearance.PLAIN,
  },
  {
    id: '16',
    name: 'Макароны, крупы, бобовые',
    url: '/',
    groups: ['Бакалея', 'Новинки', 'Хиты'],
    accent: Appearance.PLAIN,
  },
  {
    id: '17',
    name: 'Мюсли, сухие завтраки и обеды, каши',
    url: '/',
    groups: ['Бакалея', 'Новинки', 'Хиты'],
    accent: Appearance.PLAIN,
  },
];
